### ISSUE TITLE
Validasi NIK di MacOS (chrome & safari) Selalu Gagal

### ISSUE THREAD

**Issue by anwarramadha** [agraris/nusantara-valid#3]
![image](https://user-images.githubusercontent.com/15810867/109105874-5403cb80-7761-11eb-8ab8-8977426b6861.png)

**Comment by magicjar** [comment]
Oh ternyata ada bug di reformatBirthday() bagian tanggal.
Yang seharusnya tanggal lahir (perempuan) di KTP diformat dari '42' menadi '02' tetapi terformat jadi '2', sehingga saat di komparasi dengan tanggal lahir (89032 dikomparasi dengan 890302), hasilnya false.

Kalau @anwarramadha mau bantu fix boleh kok pull request.

**Comment by magicjar** [comment]
Fixed.

**Comment by anwarramadha** [comment]
terima kasih.
